import Link from "next/link"
import { notFound } from "next/navigation"
import { ChevronLeft, Instagram, MessageCircle, PackageCheck, Store } from "lucide-react"
import { PublicHeader } from "../../../components/PublicHeader"
import { formatPrice, whatsappUrl, type ProductoVarela } from "../../../lib/hechoEnVarela"
import { supabaseServer } from "../../../lib/supabaseServer"
import { ProductGallery } from "./ProductGallery"

export const revalidate = 300
export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const { data } = await supabaseServer.from("productos_varela").select("*, emprendimientos_varela(*)").eq("slug", slug).eq("activo", true).maybeSingle()
  if (!data) notFound()
  const product = data as ProductoVarela, venture = product.emprendimientos_varela!
  return <><PublicHeader items={[]} /><main className="min-h-screen bg-[#fbf7ef]"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/hecho-en-varela" className="inline-flex items-center gap-1 text-sm font-bold text-stone-600 hover:text-amber-800"><ChevronLeft className="h-4 w-4" /> Volver al catálogo</Link><div className="mt-6 grid gap-9 lg:grid-cols-2"><ProductGallery images={product.imagenes || []} name={product.nombre} /><section><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-900">{product.categoria}</span><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">{product.nombre}</h1><p className="mt-4 text-2xl font-black text-amber-900">{formatPrice(product.precio, product.consultar_precio)}</p><p className="mt-6 whitespace-pre-line text-base leading-7 text-stone-700">{product.descripcion || product.descripcion_breve}</p>{product.variantes?.length > 0 && <div className="mt-7"><h2 className="font-black">Opciones disponibles</h2><div className="mt-3 flex flex-wrap gap-2">{product.variantes.map(item => <span key={item} className="rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm">{item}</span>)}</div></div>}{(product.informacion_entrega || venture.modalidad_entrega) && <div className="mt-7 rounded-2xl border border-amber-900/10 bg-white p-4"><h2 className="flex items-center gap-2 font-black"><PackageCheck className="h-5 w-5 text-amber-800" /> Encargos, entrega o retiro</h2><p className="mt-2 text-sm leading-6 text-stone-600">{product.informacion_entrega || venture.modalidad_entrega}</p></div>}<div className="mt-7 flex items-center gap-4 border-t border-stone-200 pt-6">{venture.logo_url ? <img src={venture.logo_url} alt={venture.nombre} className="h-14 w-14 rounded-2xl object-cover" /> : <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-100"><Store className="h-6 w-6 text-amber-800" /></div>}<div><p className="text-xs font-bold uppercase tracking-wider text-stone-500">Creado por</p><Link href={`/hecho-en-varela/emprendimiento/${venture.slug}`} className="font-black hover:text-amber-800">{venture.nombre}</Link></div>{venture.instagram_url && <a href={venture.instagram_url} target="_blank" rel="noreferrer" className="ml-auto rounded-full border border-stone-300 p-2"><Instagram className="h-5 w-5" /></a>}</div><a href={whatsappUrl(venture.whatsapp, product.nombre)} target="_blank" rel="noreferrer" className="mt-7 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#25D366] px-5 text-lg font-black text-white shadow-lg hover:bg-[#20bd5a]"><MessageCircle className="h-6 w-6" /> Consultar por WhatsApp</a></section></div></div></main></>
}
