'use client'

import { useCallback, useEffect, useState } from "react"
import { BriefcaseBusiness, Check, Eye, EyeOff, Pencil, Trash2, X } from "lucide-react"
import { AdminConfirmModal } from "../../components/AdminConfirmModal"
import { formatJobDate, JOB_CATEGORIES, JOB_STATUSES, type JobOpportunity, type JobStatus } from "../../lib/jobOpportunities"

export default function AdminJobsPage() {
  const [items, setItems] = useState<JobOpportunity[]>([]), [loading, setLoading] = useState(true)
  const [visibleEnHome, setVisibleEnHome] = useState(true), [visibilitySaving, setVisibilitySaving] = useState(false), [visibilityError, setVisibilityError] = useState("")
  const [type, setType] = useState(""), [status, setStatus] = useState("pendiente"), [category, setCategory] = useState("")
  const [editing, setEditing] = useState<JobOpportunity | null>(null), [deleting, setDeleting] = useState<JobOpportunity | null>(null)
  const load = useCallback(async () => { const q = new URLSearchParams(); if(type)q.set("tipo",type);if(status)q.set("estado",status);if(category)q.set("categoria",category); const r=await fetch(`/api/admin/oportunidades-laborales?${q}`,{cache:"no-store"});const j=await r.json();if(r.ok){setItems(j.items||[]);setVisibleEnHome(j.visibleEnHome!==false)}setLoading(false)},[type,status,category])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  const changeStatus=async(id:string,next:JobStatus)=>{await fetch("/api/admin/oportunidades-laborales",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,estado:next})});void load()}
  const save=async()=>{if(!editing)return;await fetch("/api/admin/oportunidades-laborales",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)});setEditing(null);void load()}
  const remove=async()=>{if(!deleting)return;await fetch(`/api/admin/oportunidades-laborales?id=${deleting.id}`,{method:"DELETE"});setDeleting(null);void load()}
  const toggleHomeVisibility=async()=>{const next=!visibleEnHome;setVisibilitySaving(true);setVisibilityError("");const r=await fetch("/api/admin/oportunidades-laborales",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"toggle_home_visibility",visible:next})});const j=await r.json();if(r.ok)setVisibleEnHome(j.visibleEnHome===true);else setVisibilityError(j.error||"No se pudo cambiar la visibilidad en la Home.");setVisibilitySaving(false)}
  return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-950">Oportunidades Laborales</h1><p className="mt-1 text-slate-500">Moderá ofertas y búsquedas laborales.</p></div><span className="rounded-full bg-white px-4 py-2 text-sm font-semibold shadow-sm">{items.length} publicaciones</span></div>
    <div className="mt-6 flex flex-col justify-between gap-4 rounded-2xl border border-sky-200 bg-sky-50 p-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3">{visibleEnHome?<Eye className="mt-0.5 h-5 w-5 text-sky-700"/>:<EyeOff className="mt-0.5 h-5 w-5 text-slate-500"/>}<div><h2 className="font-bold text-slate-950">Visibilidad en la Home</h2><p className="mt-1 text-sm text-slate-600">{visibleEnHome?"El acceso a Oportunidades Laborales está visible en la página principal.":"El acceso está oculto en la Home; la página de oportunidades sigue disponible."}</p>{visibilityError?<p className="mt-2 text-sm font-semibold text-red-700">{visibilityError}</p>:null}</div></div><button type="button" onClick={()=>void toggleHomeVisibility()} disabled={visibilitySaving} className={`shrink-0 rounded-xl px-5 py-3 text-sm font-bold text-white transition disabled:opacity-60 ${visibleEnHome?"bg-slate-700 hover:bg-slate-600":"bg-sky-600 hover:bg-sky-500"}`}>{visibilitySaving?"Guardando...":visibleEnHome?"Ocultar de la Home":"Mostrar en la Home"}</button></div>
    <div className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-3"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border p-3"><option value="">Todos los tipos</option><option value="oferta">Buscan personal</option><option value="busqueda">Buscan trabajo</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-3"><option value="">Todos los estados</option>{JOB_STATUSES.map(v=><option key={v}>{v}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border p-3"><option value="">Todas las categorías</option>{JOB_CATEGORIES.map(v=><option key={v}>{v}</option>)}</select></div>
    {loading?<div className="py-16 text-center text-slate-500">Cargando publicaciones...</div>:items.length===0?<div className="mt-6 rounded-2xl bg-white py-16 text-center"><BriefcaseBusiness className="mx-auto h-12 w-12 text-slate-300"/><p className="mt-3 text-slate-500">No hay publicaciones con estos filtros.</p></div>:<div className="mt-6 space-y-3">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div className="min-w-0"><div className="flex flex-wrap gap-2 text-xs font-bold uppercase"><span className="rounded-full bg-sky-50 px-3 py-1 text-sky-700">{item.tipo_publicacion}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">{item.estado}</span></div><h2 className="mt-3 text-xl font-bold">{item.titulo}</h2><p className="text-sm text-slate-500">{item.nombre_publicante} · {item.categoria} · {item.localidad} · {formatJobDate(item.fecha_creacion)}</p><p className="mt-3 line-clamp-2 max-w-3xl text-sm text-slate-600">{item.descripcion}</p></div><div className="flex shrink-0 flex-wrap items-start gap-2"><button onClick={()=>void changeStatus(item.id,"activa")} title="Aprobar" className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><Check className="h-4 w-4"/></button><button onClick={()=>void changeStatus(item.id,"rechazada")} title="Rechazar" className="rounded-lg bg-amber-50 p-2 text-amber-700"><X className="h-4 w-4"/></button><button onClick={()=>void changeStatus(item.id,item.estado==="activa"?"vencida":"pendiente")} className="rounded-lg border px-3 py-2 text-xs font-semibold">{item.estado==="activa"?"Desactivar":"Pendiente"}</button><button onClick={()=>setEditing(item)} className="rounded-lg bg-blue-50 p-2 text-blue-700"><Pencil className="h-4 w-4"/></button><button onClick={()=>setDeleting(item)} className="rounded-lg bg-red-50 p-2 text-red-700"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div>}
    {editing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div className="mx-auto my-8 max-w-2xl rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Editar publicación</h2><div className="mt-5 grid gap-4"><AdminField label="Nombre" value={editing.nombre_publicante} onChange={v=>setEditing({...editing,nombre_publicante:v})}/><AdminField label="Título" value={editing.titulo} onChange={v=>setEditing({...editing,titulo:v})}/><AdminField label="Localidad" value={editing.localidad} onChange={v=>setEditing({...editing,localidad:v})}/><label className="text-sm font-semibold">Descripción<textarea rows={6} value={editing.descripcion} onChange={e=>setEditing({...editing,descripcion:e.target.value})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label></div><div className="mt-5 flex gap-3"><button onClick={()=>void save()} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Guardar</button><button onClick={()=>setEditing(null)} className="rounded-xl border px-5 py-3">Cancelar</button></div></div></div>}
    <AdminConfirmModal isOpen={Boolean(deleting)} title="Eliminar publicación" description={`Se eliminará definitivamente “${deleting?.titulo || ""}”.`} confirmLabel="Eliminar" confirmVariant="danger" onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>
  </div>
}
function AdminField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm font-semibold">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label>}
